apiVersion: v1
kind: Namespace
metadata:
  name: kubegenie
  labels:
    app: kubegenie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubegenie-backend
  namespace: kubegenie
  labels:
    app: kubegenie
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubegenie
      component: backend
  template:
    metadata:
      labels:
        app: kubegenie
        component: backend
    spec:
      containers:
      - name: backend
        image: kubegenie/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kubegenie-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://kubegenie-redis:6379/0"
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kubegenie-secrets
              key: api-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kubegenie-backend
  namespace: kubegenie
  labels:
    app: kubegenie
    component: backend
spec:
  selector:
    app: kubegenie
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP