apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubegenie-ui
  namespace: kubegenie
  labels:
    app: kubegenie
    component: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubegenie
      component: ui
  template:
    metadata:
      labels:
        app: kubegenie
        component: ui
    spec:
      containers:
      - name: ui
        image: kubegenie/ui:latest
        ports:
        - containerPort: 7860
        env:
        - name: KUBEGENIE_API_URL
          value: "http://kubegenie-backend:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kubegenie-ui
  namespace: kubegenie
  labels:
    app: kubegenie
    component: ui
spec:
  selector:
    app: kubegenie
    component: ui
  ports:
  - port: 7860
    targetPort: 7860
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubegenie-ingress
  namespace: kubegenie
  labels:
    app: kubegenie
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - kubegenie.example.com
    secretName: kubegenie-tls
  rules:
  - host: kubegenie.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubegenie-ui
            port:
              number: 7860
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: kubegenie-backend
            port:
              number: 8000